site_name: Simulations for revision 1 of Galichon-Salanie JAppE

site_url: https://github.pages.io/bsalanie/rev1_simuls

repo_url: https://github.com/bsalanie/rev1_simuls

theme:
  palette:
    scheme: preference
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - search.highlight
    - navigation.expand
    - navigation.tabs
#   custom_dir: "docs/overrides"

plugins:
  - search
  - mkdocstrings
#  - git-revision-date

markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - toc:
      permalink: true
  - admonition # add notes, warnings...
  - codehilite
  - toc
  - pymdownx.arithmatex # for LaTeX
extra_javascript: # for arithmatex
  - "https://polyfill.io/v3/polyfill.min.js?features=es6"
  - "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"

nav:
  - Home: index.md
  #    - Installation: installation.md
  #    - Usage: usage.md
  #    - Contributing: contributing.md
  #    - FAQ: faq.md
  # - Report Issues: https://github.com/bsalanie/bs_cupid_try/issues
  - API Reference:
      - General Utilities: utils.md
      - Specification: specification.md
      - Reading the Data: read_data.md
      - Generating Plots: plots.md
